---
abstract: 'basic edlib library'
author:
  - 'Christos Argyropoulos <chrisarg@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.032, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Bio-SeqAlignment-Components-Libraries-edlib
requires:
  Alien::SeqAlignment::edlib: '0'
  Carp: '0'
  Env: '0'
  Exporter: '0'
  FFI::Platypus: '0'
  FFI::Platypus::Record: '0'
  Inline: '0'
  constant: '0'
  strict: '0'
  warnings: '0'
version: '0.02'
x_generated_by_perl: v5.38.0
x_serialization_backend: 'YAML::Tiny version 1.74'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
